/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TREE = 1;
  /** RegularExpression Id. */
  int NODES = 2;
  /** RegularExpression Id. */
  int LPAREN = 3;
  /** RegularExpression Id. */
  int RPAREN = 4;
  /** RegularExpression Id. */
  int MINOR = 5;
  /** RegularExpression Id. */
  int MAJOR = 6;
  /** RegularExpression Id. */
  int COLON = 7;
  /** RegularExpression Id. */
  int SEMICOLON = 8;
  /** RegularExpression Id. */
  int COMMA = 9;
  /** RegularExpression Id. */
  int NODEIDENTIFIER = 10;
  /** RegularExpression Id. */
  int STRING = 11;
  /** RegularExpression Id. */
  int NUMBER = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"TREE\"",
    "\"NODES\"",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\">\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "<NODEIDENTIFIER>",
    "<STRING>",
    "<NUMBER>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
  };

}
